name: 'Build (All)'

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  controller:
    name: 'Test'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@main
        with:
          sparse-checkout: '.github/workflows/create-test-plan.py'
      - uses: mymindstorm/setup-emsdk@v15
        with:
          version: 3.1.48
      - name: 'init'
        run: |
          git clone https://github.com/libusb/libusb
          cd libusb
          sudo apt update
          sudo apt install -y autoconf automake libtool libudev-dev m4 pkg-config clang llvm
          ./bootstrap.sh
          mkdir ~/libusb_output
          emconfigure .private/ci-build.sh --build-dir build-emscripten --no-test --install -- --host=wasm32-unknown-emscripten --prefix=${{ github.workspace }}/libusb_output
      - name: 'Upload binary package'
        uses: actions/upload-artifact@v7
        with:
          if-no-files-found: error
          name: 'output.zip'
          path: ${{ github.workspace }}/libusb_output